/*  --------- Project Euler Number 45 -----------
		//Triangular,pentagonal, and hexagonal
		
		Problem Statement-

Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.

*/
//Just use relations to check if a given number is also Pn and Hn: solution : 1533776805

 #include <iostream>
 #include <cmath>
 
 int main()
 {
 	bool found = false;
 	long n = 286;//Starting point from problem statement
 	double test_case1 = 0.,test_case2 = 0.;
 	while(found ==false)
 	{
 		test_case1 = (1. + sqrt(1.+12.*n*n + 12.*n))/6.;
 		test_case2 = (1. + sqrt(1.+4.*n*n + 4.*n))/4.;
 		if(test_case1 ==(long)test_case1 && test_case2 ==(long)test_case2)
 		{
 			found =true;
 		}
 		n++;
  	}
 	n--;
 	long next_num =n*(n+1)/2; 
 	std::cout<<"The next triangle number that is also pentagonal and hexagonal is equal to "<< next_num<<std::endl;
 
 	return 0;
 }